#!/usr/bin/env bash
set -e
echo "Remote hook"

cd "$1"

if [ "$2" == "0" ]; then
    # Run code for full release
    echo "Full release hook"
fi

if [ "$2" == "1" ]; then
    # Run code for incremental release
    echo "Incremental release hook"
fi