#!/usr/bin/env bash

# SERVERS
#
production_host=192.168.20.20
production_port=22
production_user=ubuntu
production_identity=~/.ssh/id_rsa
production_cwd=/home/ubuntu/website

staging_host=192.168.20.20
staging_port=22
staging_user=ubuntu
staging_identity=~/.ssh/id_rsa
staging_cwd=/home/ubuntu/website

# PRE HOOKS
# array of bash scripts which are executed before the deployment process
#
pre_hooks=(
    pre
)

# REMOTE HOOKS
# array of bash scripts which are executed on the server after the transfer of files
#
remote_hooks=(
    remote
)

# POST HOOKS
# array of bash scripts which are executed after the deployment process
#
post_hooks=(
    post
)

# IGNORES
# array of ignored files and folders
# the syntax must match zip --exclude patterns
# check the documentation at https://linux.die.net/man/1/zip
# To test the ignores use: depy pack-list
#
ignores=(
    "*.git*"
)

# SHARED
# array shared files and folders which are kept between releases
#
shared=(
    logs
)

# KEEP RELEASES
# the number of releases to keep on the server for rollbacks
#
keep_releases=4
